#define YY_myparser_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

    #include <stdio.h>
    extern int yylex();
    int yyerror(char* s);
    #include<string.h>
    void test_parser();
    int result;

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_myparser_BISON 1

#ifndef YY_myparser_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_myparser_COMPATIBILITY 1
 #else
  #define  YY_myparser_COMPATIBILITY 0
 #endif
#endif

#if YY_myparser_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_myparser_LTYPE
   #define YY_myparser_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_myparser_STYPE 
   #define YY_myparser_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_myparser_DEBUG
   #define  YY_myparser_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_myparser_USE_GOTO
  #define YY_myparser_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_myparser_USE_GOTO
 #define YY_myparser_USE_GOTO 0
#endif

#ifndef YY_myparser_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_myparser_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_myparser_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_myparser_DEBUG */
#endif


#ifndef YY_myparser_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_myparser_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_myparser_LSP_NEEDED
#ifndef YY_myparser_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_myparser_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_myparser_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_myparser_STYPE
#define YY_myparser_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_myparser_PARSE
#define YY_myparser_PARSE yyparse
#endif
#ifndef YY_myparser_LEX
#define YY_myparser_LEX yylex
#endif
#ifndef YY_myparser_LVAL
#define YY_myparser_LVAL yylval
#endif
#ifndef YY_myparser_LLOC
#define YY_myparser_LLOC yylloc
#endif
#ifndef YY_myparser_CHAR
#define YY_myparser_CHAR yychar
#endif
#ifndef YY_myparser_NERRS
#define YY_myparser_NERRS yynerrs
#endif
#ifndef YY_myparser_DEBUG_FLAG
#define YY_myparser_DEBUG_FLAG yydebug
#endif
#ifndef YY_myparser_ERROR
#define YY_myparser_ERROR yyerror
#endif

#ifndef YY_myparser_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_myparser_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_myparser_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_myparser_PARSE_PARAM
  #define YY_myparser_PARSE_PARAM void
 #endif
#endif

#if YY_myparser_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_myparser_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_myparser_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_myparser_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_myparser_PURE
#  ifndef YYPURE
#    define YYPURE YY_myparser_PURE
#  endif
#endif

#ifdef YY_myparser_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_myparser_DEBUG 
#  endif
#endif

#ifndef YY_myparser_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_myparser_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_myparser_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_myparser_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	LET	258
#define	MUT	259
#define	ENUM	260
#define	EXTERN	261
#define	IMPL	262
#define	MATCH	263
#define	PUB	264
#define	REF	265
#define	RETURN	266
#define	SELF	267
#define	STATIC	268
#define	SUPER	269
#define	TRAIT	270
#define	TYPE	271
#define	UNSAFE	272
#define	WHERE	273
#define	ASYNC	274
#define	AWAIT	275
#define	USE	276
#define	MOD	277
#define	MAIN	278
#define	FN	279
#define	PRINTLN	280
#define	STRINTERPOLATION	281
#define	TRUE	282
#define	FALSE	283
#define	ID	284
#define	INT	285
#define	FLOAT	286
#define	BOOL	287
#define	STRUCT	288
#define	STRING	289
#define	NUMBER	290
#define	ARRAY	291
#define	STRSLICE	292
#define	ARROW	293
#define	IF	294
#define	ELSE	295
#define	LOOP	296
#define	WHILE	297
#define	FOR	298
#define	IN	299
#define	BREAK	300
#define	CONTINUE	301
#define	LOGICALNOT	302
#define	LOGICALAND	303
#define	LOGICALOR	304
#define	ADD	305
#define	SUBTRACT	306
#define	MULTIPLY	307
#define	DIVIDE	308
#define	ASSIGN	309
#define	REMAINDER	310
#define	ADDEQ	311
#define	SUBTRACTEQ	312
#define	MULTIPLYEQ	313
#define	DIVIDEEQ	314
#define	REMAINDEREQ	315
#define	EQUALTO	316
#define	NOTEQUALTO	317
#define	GT	318
#define	GTEQ	319
#define	LT	320
#define	LTEQ	321
#define	SEMICOLON	322
#define	COMMA	323
#define	PERIOD	324
#define	COLON	325
#define	QUESTION_MARK	326
#define	LPAREN	327
#define	RPAREN	328
#define	LBRACE	329
#define	RBRACE	330
#define	LSQUAREBRAC	331
#define	RSQUAREBRAC	332
#define	COMMENT	333


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_myparser_CLASS
#define YY_myparser_CLASS myparser
#endif
#ifndef YY_myparser_INHERIT
#define YY_myparser_INHERIT
#endif
#ifndef YY_myparser_MEMBERS
#define YY_myparser_MEMBERS 
#endif
#ifndef YY_myparser_LEX_BODY
#define YY_myparser_LEX_BODY  
#endif
#ifndef YY_myparser_ERROR_BODY
#define YY_myparser_ERROR_BODY  
#endif
#ifndef YY_myparser_CONSTRUCTOR_PARAM
#define YY_myparser_CONSTRUCTOR_PARAM
#endif
#ifndef YY_myparser_CONSTRUCTOR_CODE
#define YY_myparser_CONSTRUCTOR_CODE
#endif
#ifndef YY_myparser_CONSTRUCTOR_INIT
#define YY_myparser_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_myparser_USE_CONST_TOKEN
#define YY_myparser_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_myparser_USE_CONST_TOKEN != 0
#ifndef YY_myparser_ENUM_TOKEN
#define YY_myparser_ENUM_TOKEN yy_myparser_enum_token
#endif
#endif

class YY_myparser_CLASS YY_myparser_INHERIT
{
public: 
#if YY_myparser_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int LET;
static const int MUT;
static const int ENUM;
static const int EXTERN;
static const int IMPL;
static const int MATCH;
static const int PUB;
static const int REF;
static const int RETURN;
static const int SELF;
static const int STATIC;
static const int SUPER;
static const int TRAIT;
static const int TYPE;
static const int UNSAFE;
static const int WHERE;
static const int ASYNC;
static const int AWAIT;
static const int USE;
static const int MOD;
static const int MAIN;
static const int FN;
static const int PRINTLN;
static const int STRINTERPOLATION;
static const int TRUE;
static const int FALSE;
static const int ID;
static const int INT;
static const int FLOAT;
static const int BOOL;
static const int STRUCT;
static const int STRING;
static const int NUMBER;
static const int ARRAY;
static const int STRSLICE;
static const int ARROW;
static const int IF;
static const int ELSE;
static const int LOOP;
static const int WHILE;
static const int FOR;
static const int IN;
static const int BREAK;
static const int CONTINUE;
static const int LOGICALNOT;
static const int LOGICALAND;
static const int LOGICALOR;
static const int ADD;
static const int SUBTRACT;
static const int MULTIPLY;
static const int DIVIDE;
static const int ASSIGN;
static const int REMAINDER;
static const int ADDEQ;
static const int SUBTRACTEQ;
static const int MULTIPLYEQ;
static const int DIVIDEEQ;
static const int REMAINDEREQ;
static const int EQUALTO;
static const int NOTEQUALTO;
static const int GT;
static const int GTEQ;
static const int LT;
static const int LTEQ;
static const int SEMICOLON;
static const int COMMA;
static const int PERIOD;
static const int COLON;
static const int QUESTION_MARK;
static const int LPAREN;
static const int RPAREN;
static const int LBRACE;
static const int RBRACE;
static const int LSQUAREBRAC;
static const int RSQUAREBRAC;
static const int COMMENT;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_myparser_ENUM_TOKEN { YY_myparser_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,LET=258
	,MUT=259
	,ENUM=260
	,EXTERN=261
	,IMPL=262
	,MATCH=263
	,PUB=264
	,REF=265
	,RETURN=266
	,SELF=267
	,STATIC=268
	,SUPER=269
	,TRAIT=270
	,TYPE=271
	,UNSAFE=272
	,WHERE=273
	,ASYNC=274
	,AWAIT=275
	,USE=276
	,MOD=277
	,MAIN=278
	,FN=279
	,PRINTLN=280
	,STRINTERPOLATION=281
	,TRUE=282
	,FALSE=283
	,ID=284
	,INT=285
	,FLOAT=286
	,BOOL=287
	,STRUCT=288
	,STRING=289
	,NUMBER=290
	,ARRAY=291
	,STRSLICE=292
	,ARROW=293
	,IF=294
	,ELSE=295
	,LOOP=296
	,WHILE=297
	,FOR=298
	,IN=299
	,BREAK=300
	,CONTINUE=301
	,LOGICALNOT=302
	,LOGICALAND=303
	,LOGICALOR=304
	,ADD=305
	,SUBTRACT=306
	,MULTIPLY=307
	,DIVIDE=308
	,ASSIGN=309
	,REMAINDER=310
	,ADDEQ=311
	,SUBTRACTEQ=312
	,MULTIPLYEQ=313
	,DIVIDEEQ=314
	,REMAINDEREQ=315
	,EQUALTO=316
	,NOTEQUALTO=317
	,GT=318
	,GTEQ=319
	,LT=320
	,LTEQ=321
	,SEMICOLON=322
	,COMMA=323
	,PERIOD=324
	,COLON=325
	,QUESTION_MARK=326
	,LPAREN=327
	,RPAREN=328
	,LBRACE=329
	,RBRACE=330
	,LSQUAREBRAC=331
	,RSQUAREBRAC=332
	,COMMENT=333


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_myparser_PARSE (YY_myparser_PARSE_PARAM);
 virtual void YY_myparser_ERROR(char *msg) YY_myparser_ERROR_BODY;
#ifdef YY_myparser_PURE
#ifdef YY_myparser_LSP_NEEDED
 virtual int  YY_myparser_LEX (YY_myparser_STYPE *YY_myparser_LVAL,YY_myparser_LTYPE *YY_myparser_LLOC) YY_myparser_LEX_BODY;
#else
 virtual int  YY_myparser_LEX (YY_myparser_STYPE *YY_myparser_LVAL) YY_myparser_LEX_BODY;
#endif
#else
 virtual int YY_myparser_LEX() YY_myparser_LEX_BODY;
 YY_myparser_STYPE YY_myparser_LVAL;
#ifdef YY_myparser_LSP_NEEDED
 YY_myparser_LTYPE YY_myparser_LLOC;
#endif
 int   YY_myparser_NERRS;
 int    YY_myparser_CHAR;
#endif
#if YY_myparser_DEBUG != 0
 int YY_myparser_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_myparser_CLASS(YY_myparser_CONSTRUCTOR_PARAM);
public:
 YY_myparser_MEMBERS 
};
/* other declare folow */
#if YY_myparser_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_myparser_CLASS::LET=258;
const int YY_myparser_CLASS::MUT=259;
const int YY_myparser_CLASS::ENUM=260;
const int YY_myparser_CLASS::EXTERN=261;
const int YY_myparser_CLASS::IMPL=262;
const int YY_myparser_CLASS::MATCH=263;
const int YY_myparser_CLASS::PUB=264;
const int YY_myparser_CLASS::REF=265;
const int YY_myparser_CLASS::RETURN=266;
const int YY_myparser_CLASS::SELF=267;
const int YY_myparser_CLASS::STATIC=268;
const int YY_myparser_CLASS::SUPER=269;
const int YY_myparser_CLASS::TRAIT=270;
const int YY_myparser_CLASS::TYPE=271;
const int YY_myparser_CLASS::UNSAFE=272;
const int YY_myparser_CLASS::WHERE=273;
const int YY_myparser_CLASS::ASYNC=274;
const int YY_myparser_CLASS::AWAIT=275;
const int YY_myparser_CLASS::USE=276;
const int YY_myparser_CLASS::MOD=277;
const int YY_myparser_CLASS::MAIN=278;
const int YY_myparser_CLASS::FN=279;
const int YY_myparser_CLASS::PRINTLN=280;
const int YY_myparser_CLASS::STRINTERPOLATION=281;
const int YY_myparser_CLASS::TRUE=282;
const int YY_myparser_CLASS::FALSE=283;
const int YY_myparser_CLASS::ID=284;
const int YY_myparser_CLASS::INT=285;
const int YY_myparser_CLASS::FLOAT=286;
const int YY_myparser_CLASS::BOOL=287;
const int YY_myparser_CLASS::STRUCT=288;
const int YY_myparser_CLASS::STRING=289;
const int YY_myparser_CLASS::NUMBER=290;
const int YY_myparser_CLASS::ARRAY=291;
const int YY_myparser_CLASS::STRSLICE=292;
const int YY_myparser_CLASS::ARROW=293;
const int YY_myparser_CLASS::IF=294;
const int YY_myparser_CLASS::ELSE=295;
const int YY_myparser_CLASS::LOOP=296;
const int YY_myparser_CLASS::WHILE=297;
const int YY_myparser_CLASS::FOR=298;
const int YY_myparser_CLASS::IN=299;
const int YY_myparser_CLASS::BREAK=300;
const int YY_myparser_CLASS::CONTINUE=301;
const int YY_myparser_CLASS::LOGICALNOT=302;
const int YY_myparser_CLASS::LOGICALAND=303;
const int YY_myparser_CLASS::LOGICALOR=304;
const int YY_myparser_CLASS::ADD=305;
const int YY_myparser_CLASS::SUBTRACT=306;
const int YY_myparser_CLASS::MULTIPLY=307;
const int YY_myparser_CLASS::DIVIDE=308;
const int YY_myparser_CLASS::ASSIGN=309;
const int YY_myparser_CLASS::REMAINDER=310;
const int YY_myparser_CLASS::ADDEQ=311;
const int YY_myparser_CLASS::SUBTRACTEQ=312;
const int YY_myparser_CLASS::MULTIPLYEQ=313;
const int YY_myparser_CLASS::DIVIDEEQ=314;
const int YY_myparser_CLASS::REMAINDEREQ=315;
const int YY_myparser_CLASS::EQUALTO=316;
const int YY_myparser_CLASS::NOTEQUALTO=317;
const int YY_myparser_CLASS::GT=318;
const int YY_myparser_CLASS::GTEQ=319;
const int YY_myparser_CLASS::LT=320;
const int YY_myparser_CLASS::LTEQ=321;
const int YY_myparser_CLASS::SEMICOLON=322;
const int YY_myparser_CLASS::COMMA=323;
const int YY_myparser_CLASS::PERIOD=324;
const int YY_myparser_CLASS::COLON=325;
const int YY_myparser_CLASS::QUESTION_MARK=326;
const int YY_myparser_CLASS::LPAREN=327;
const int YY_myparser_CLASS::RPAREN=328;
const int YY_myparser_CLASS::LBRACE=329;
const int YY_myparser_CLASS::RBRACE=330;
const int YY_myparser_CLASS::LSQUAREBRAC=331;
const int YY_myparser_CLASS::RSQUAREBRAC=332;
const int YY_myparser_CLASS::COMMENT=333;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_myparser_CLASS::token */
#endif
/*apres const  */
YY_myparser_CLASS::YY_myparser_CLASS(YY_myparser_CONSTRUCTOR_PARAM) YY_myparser_CONSTRUCTOR_INIT
{
#if YY_myparser_DEBUG != 0
YY_myparser_DEBUG_FLAG=0;
#endif
YY_myparser_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		131
#define	YYFLAG		-32768
#define	YYNTBASE	79

#define YYTRANSLATE(x) ((unsigned)(x) <= 333 ? yytranslate[x] : 98)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    63,    64,    65,
    66,    67,    68,    69,    70,    71,    72,    73,    74,    75,
    76,    77,    78
};

#if YY_myparser_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     3,    12,    13,    15,    16,    19,    20,    22,
    24,    26,    28,    31,    33,    34,    37,    40,    43,    46,
    48,    50,    52,    53,    62,    69,    70,    77,    82,    89,
    90,    95,    96,   101,   102,   106,   107,   112,   113,   118,
   119,   124,   131,   137,   142,   147,   153,   160,   161,   167,
   171,   175,   177,   181,   182,   184,   186,   188,   190,   192,
   194,   196,   198,   200,   202,   204,   206,   208,   210,   212,
   214,   216,   218,   220,   222,   224,   226,   228,   232
};

static const short yyrhs[] = {    80,
     0,     0,    24,    29,    72,    94,    73,    82,    84,    80,
     0,     0,    68,     0,     0,    38,    83,     0,     0,    30,
     0,    31,     0,    32,     0,    37,     0,    72,    73,     0,
    97,     0,     0,    87,    85,     0,    86,    85,     0,    88,
    85,     0,    89,    85,     0,    90,     0,    92,     0,    91,
     0,     0,    25,    72,    95,    68,    95,    73,    67,    86,
     0,    25,    72,    95,    73,    67,    86,     0,     0,     3,
    29,    54,    93,    67,    87,     0,     3,    29,    67,    87,
     0,     3,    29,    54,    95,    67,    87,     0,     0,    39,
    93,    97,    88,     0,     0,    88,    40,    97,    89,     0,
     0,    41,    97,    90,     0,     0,    42,    93,    97,    91,
     0,     0,    43,    93,    97,    92,     0,     0,    95,    96,
    95,    93,     0,    95,    96,    95,    96,    95,    93,     0,
    29,    72,    94,    73,    67,     0,    29,    72,    94,    73,
     0,    29,    72,    95,    73,     0,    29,    69,    29,    72,
    73,     0,    29,    69,    29,    72,    94,    73,     0,     0,
    29,    70,    83,    81,    94,     0,    29,    70,    83,     0,
    95,    68,    95,     0,    95,     0,    95,    68,    94,     0,
     0,    29,     0,    35,     0,    32,     0,    34,     0,    47,
     0,    48,     0,    49,     0,    50,     0,    51,     0,    52,
     0,    53,     0,    55,     0,    56,     0,    57,     0,    58,
     0,    59,     0,    60,     0,    61,     0,    62,     0,    63,
     0,    64,     0,    65,     0,    66,     0,    74,    93,    75,
     0,    74,    85,    75,     0
};

#endif

#if (YY_myparser_DEBUG != 0) || defined(YY_myparser_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   111,   111,   113,   113,   115,   115,   116,   116,   117,   118,
   119,   120,   121,   123,   123,   126,   127,   128,   129,   130,
   131,   132,   133,   135,   136,   137,   139,   140,   141,   142,
   144,   144,   146,   146,   148,   148,   150,   150,   152,   152,
   154,   155,   156,   157,   158,   159,   160,   161,   163,   164,
   165,   166,   167,   168,   170,   170,   170,   170,   171,   171,
   171,   171,   171,   171,   171,   171,   171,   171,   172,   172,
   172,   172,   172,   172,   172,   172,   172,   175,   175
};

static const char * const yytname[] = {   "$","error","$illegal.","LET","MUT",
"ENUM","EXTERN","IMPL","MATCH","PUB","REF","RETURN","SELF","STATIC","SUPER",
"TRAIT","TYPE","UNSAFE","WHERE","ASYNC","AWAIT","USE","MOD","MAIN","FN","PRINTLN",
"STRINTERPOLATION","TRUE","FALSE","ID","INT","FLOAT","BOOL","STRUCT","STRING",
"NUMBER","ARRAY","STRSLICE","ARROW","IF","ELSE","LOOP","WHILE","FOR","IN","BREAK",
"CONTINUE","LOGICALNOT","LOGICALAND","LOGICALOR","ADD","SUBTRACT","MULTIPLY",
"DIVIDE","ASSIGN","REMAINDER","ADDEQ","SUBTRACTEQ","MULTIPLYEQ","DIVIDEEQ","REMAINDEREQ",
"EQUALTO","NOTEQUALTO","GT","GTEQ","LT","LTEQ","SEMICOLON","COMMA","PERIOD",
"COLON","QUESTION_MARK","LPAREN","RPAREN","LBRACE","RBRACE","LSQUAREBRAC","RSQUAREBRAC",
"COMMENT","start","function","comma","return_value","return_type","function_body",
"statements","print_stmt","var_decl","if_statement","if_else_statement","loop_statement",
"while_loop_statement","for_loop_statement","expression","parameter","operand",
"operator","block",""
};
#endif

static const short yyr1[] = {     0,
    79,    79,    80,    80,    81,    81,    82,    82,    83,    83,
    83,    83,    83,    84,    84,    85,    85,    85,    85,    85,
    85,    85,    85,    86,    86,    86,    87,    87,    87,    87,
    88,    88,    89,    89,    90,    90,    91,    91,    92,    92,
    93,    93,    93,    93,    93,    93,    93,    93,    94,    94,
    94,    94,    94,    94,    95,    95,    95,    95,    96,    96,
    96,    96,    96,    96,    96,    96,    96,    96,    96,    96,
    96,    96,    96,    96,    96,    96,    96,    97,    97
};

static const short yyr2[] = {     0,
     1,     0,     8,     0,     1,     0,     2,     0,     1,     1,
     1,     1,     2,     1,     0,     2,     2,     2,     2,     1,
     1,     1,     0,     8,     6,     0,     6,     4,     6,     0,
     4,     0,     4,     0,     3,     0,     4,     0,     4,     0,
     4,     6,     5,     4,     4,     5,     6,     0,     5,     3,
     3,     1,     3,     0,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     3,     3
};

static const short yydefact[] = {     2,
     0,     1,     0,    54,    55,    57,    58,    56,     0,    52,
     0,     8,    54,     9,    10,    11,    12,     0,     6,     0,
    15,    53,    51,    13,     5,    54,     7,    23,     4,    14,
    49,     0,     0,    55,    48,     0,    48,    48,     0,    23,
    23,    23,    23,    20,    22,    21,     0,     0,     3,     0,
     0,     0,    54,     0,    36,     0,     0,    79,    17,    16,
     0,    18,    19,    78,    59,    60,    61,    62,    63,    64,
    65,    66,    67,    68,    69,    70,    71,    72,    73,    74,
    75,    76,    77,     0,    48,    30,    55,     0,     0,     0,
     0,    32,    35,    38,    40,    34,    48,     0,     0,    28,
     0,     0,     0,    44,    45,    31,    37,    39,     0,    33,
    41,     0,    30,    30,     0,    26,    46,     0,    43,    48,
    27,    29,     0,    25,    47,    42,    26,    24,     0,     0,
     0
};

static const short yydefgoto[] = {   129,
     2,    26,    21,    19,    29,    39,    40,    41,    42,    43,
    44,    45,    46,    47,     9,    48,    84,    30
};

static const short yypact[] = {   -21,
   -18,-32768,   -42,    31,   -36,-32768,-32768,-32768,   -37,   -28,
   -14,    10,    31,-32768,-32768,-32768,-32768,   -23,   -11,   -14,
     0,-32768,   -28,-32768,-32768,    31,-32768,     3,   -21,-32768,
-32768,    53,   -10,   -13,    61,     0,    61,    61,     9,    28,
    28,    36,    28,-32768,-32768,-32768,    17,   121,-32768,   -46,
    93,    56,    31,     0,    57,     0,     0,-32768,-32768,-32768,
     0,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,    93,    61,    91,-32768,   -49,    51,    27,
   -48,    87,-32768,    82,    90,    33,    54,    67,   100,-32768,
    93,    68,   -22,    69,-32768,-32768,-32768,-32768,    97,-32768,
-32768,    93,    91,    91,    65,   115,-32768,    70,-32768,    61,
-32768,-32768,    77,-32768,-32768,-32768,   115,-32768,   145,   154,
-32768
};

static const short yypgoto[] = {-32768,
   146,-32768,-32768,   168,-32768,    89,  -101,   -59,   -63,    94,
   134,    98,    96,   -33,   -12,    -4,    99,    85
};


#define	YYLAST		196


static const short yytable[] = {    10,
    22,    54,     1,    56,    57,    32,     5,    85,    23,     6,
     3,     7,     8,    31,   124,    14,    15,    16,   101,    13,
    86,    10,    17,   102,   105,   128,   100,    33,   106,     4,
    32,    34,   109,    11,     6,    12,     7,     8,    32,    13,
    90,    35,   -26,    36,    37,    38,    88,    20,    91,    24,
   117,    98,    33,   121,   122,    52,    25,    18,    53,     5,
    33,    51,     6,   111,     7,     8,    35,   -26,    36,    37,
    38,    35,   -32,    28,    35,    61,    36,    37,    38,    97,
    99,    50,    34,    58,    89,     6,   126,     7,     8,    34,
   118,    64,     6,    32,     7,     8,   115,    36,    10,   104,
    65,    66,    67,    68,    69,    70,    71,   120,    72,    73,
    74,    75,    76,    77,    78,    79,    80,    81,    82,    83,
    55,    87,   103,    37,     6,    35,     7,     8,    59,    60,
    62,    63,    38,   113,   116,   119,    61,   123,    92,    33,
    94,    95,   125,   127,   130,    96,    65,    66,    67,    68,
    69,    70,    71,   131,    72,    73,    74,    75,    76,    77,
    78,    79,    80,    81,    82,    83,   114,    65,    66,    67,
    68,    69,    70,    71,    49,    72,    73,    74,    75,    76,
    77,    78,    79,    80,    81,    82,    83,    27,    93,   110,
   108,   107,     0,     0,     0,   112
};

static const short yycheck[] = {     4,
    13,    35,    24,    37,    38,     3,    29,    54,    13,    32,
    29,    34,    35,    26,   116,    30,    31,    32,    68,    68,
    67,    26,    37,    73,    73,   127,    86,    25,    92,    72,
     3,    29,    96,    70,    32,    73,    34,    35,     3,    68,
    53,    39,    40,    41,    42,    43,    51,    38,    53,    73,
    73,    85,    25,   113,   114,    69,    68,    72,    72,    29,
    25,    72,    32,    97,    34,    35,    39,    40,    41,    42,
    43,    39,    40,    74,    39,    40,    41,    42,    43,    84,
    85,    29,    29,    75,    29,    32,   120,    34,    35,    29,
   103,    75,    32,     3,    34,    35,   101,    41,   103,    73,
    47,    48,    49,    50,    51,    52,    53,   112,    55,    56,
    57,    58,    59,    60,    61,    62,    63,    64,    65,    66,
    36,    29,    72,    42,    32,    39,    34,    35,    40,    41,
    42,    43,    43,    67,    67,    67,    40,    73,    54,    25,
    56,    57,    73,    67,     0,    61,    47,    48,    49,    50,
    51,    52,    53,     0,    55,    56,    57,    58,    59,    60,
    61,    62,    63,    64,    65,    66,    67,    47,    48,    49,
    50,    51,    52,    53,    29,    55,    56,    57,    58,    59,
    60,    61,    62,    63,    64,    65,    66,    20,    55,    96,
    95,    94,    -1,    -1,    -1,    97
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_myparser_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_myparser_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_myparser_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_myparser_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_myparser_CHAR = (token), YY_myparser_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_myparser_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_myparser_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_myparser_PURE
/* UNPURE */
#define YYLEX           YY_myparser_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_myparser_CHAR;                      /*  the lookahead symbol        */
YY_myparser_STYPE      YY_myparser_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_myparser_NERRS;                 /*  number of parse errors so far */
#ifdef YY_myparser_LSP_NEEDED
YY_myparser_LTYPE YY_myparser_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_myparser_LSP_NEEDED
#define YYLEX           YY_myparser_LEX(&YY_myparser_LVAL, &YY_myparser_LLOC)
#else
#define YYLEX           YY_myparser_LEX(&YY_myparser_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_myparser_DEBUG != 0
int YY_myparser_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_myparser_CLASS::
#endif
     YY_myparser_PARSE(YY_myparser_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_myparser_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_myparser_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_myparser_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_myparser_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_myparser_LSP_NEEDED
  YY_myparser_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_myparser_LTYPE *yyls = yylsa;
  YY_myparser_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_myparser_PURE
  int YY_myparser_CHAR;
  YY_myparser_STYPE YY_myparser_LVAL;
  int YY_myparser_NERRS;
#ifdef YY_myparser_LSP_NEEDED
  YY_myparser_LTYPE YY_myparser_LLOC;
#endif
#endif

  YY_myparser_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_myparser_DEBUG != 0
  if (YY_myparser_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_myparser_NERRS = 0;
  YY_myparser_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_myparser_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_myparser_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_myparser_LSP_NEEDED
      YY_myparser_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_myparser_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_myparser_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_myparser_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_myparser_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_myparser_LSP_NEEDED
      yyls = (YY_myparser_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_myparser_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_myparser_DEBUG != 0
      if (YY_myparser_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_myparser_DEBUG != 0
  if (YY_myparser_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_myparser_CHAR == YYEMPTY)
    {
#if YY_myparser_DEBUG != 0
      if (YY_myparser_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_myparser_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_myparser_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_myparser_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_myparser_DEBUG != 0
      if (YY_myparser_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_myparser_CHAR);

#if YY_myparser_DEBUG != 0
      if (YY_myparser_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_myparser_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_myparser_CHAR, YY_myparser_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_myparser_DEBUG != 0
  if (YY_myparser_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_myparser_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_myparser_CHAR != YYEOF)
    YY_myparser_CHAR = YYEMPTY;

  *++yyvsp = YY_myparser_LVAL;
#ifdef YY_myparser_LSP_NEEDED
  *++yylsp = YY_myparser_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_myparser_DEBUG != 0
  if (YY_myparser_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_myparser_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_myparser_DEBUG != 0
  if (YY_myparser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_myparser_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_myparser_LLOC.first_line;
      yylsp->first_column = YY_myparser_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_myparser_NERRS;

#ifdef YY_myparser_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_myparser_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_myparser_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_myparser_ERROR_VERBOSE */
	YY_myparser_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_myparser_CHAR == YYEOF)
	YYABORT;

#if YY_myparser_DEBUG != 0
      if (YY_myparser_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_myparser_CHAR, yytname[yychar1]);
#endif

      YY_myparser_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_myparser_LSP_NEEDED
  yylsp--;
#endif

#if YY_myparser_DEBUG != 0
  if (YY_myparser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_myparser_DEBUG != 0
  if (YY_myparser_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_myparser_LVAL;
#ifdef YY_myparser_LSP_NEEDED
  *++yylsp = YY_myparser_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 177 "parser.y"



int main(int argc, char *argv[]) {
  extern FILE *yyin;
  yyin = fopen( argv[1], "r");
  yyparse ();

  return 0;
}

int yyerror(char *s){
    extern int yylineno;
    fprintf(stderr,"Error occured at line %d: %s\n",yylineno,s);
    return 0;
}